---
- name: Delete stage tests
  hosts: molecule-samson
  tasks:
    - name: Create a random permalink to not clash with other tests
      set_fact:
        project_permalink: '{{ 99999999 | random | to_uuid }}'
        stage_permalink: '{{ 99999999 | random | to_uuid }}'

    - debug: var=project_permalink
    - debug: var=stage_permalink

    - name: Create project
      register: project_result
      samson_project:
        url: http://localhost:9080
        token: token
        permalink: '{{ project_permalink }}'
        name: dotfiles
        repository_url: https://github.com/danihodovic/.dotfiles

    - name: Create stage
      register: result
      samson_stage:
        url: http://localhost:9080
        token: token
        project_permalink: '{{ project_permalink }}'
        permalink: '{{ stage_permalink }}'
        name: test

    - name: Delete stage
      register: result
      samson_stage: &params
        state: absent
        url: http://localhost:9080
        token: token
        project_permalink: '{{ project_result.project.permalink }}'
        permalink: '{{ stage_permalink }}'

    - name: Assert that the deletion returned a changed task
      assert:
        that:
          - result is changed

    - name: Delete the project again
      register: result
      samson_stage:
        <<: *params

    - name: Assert that nothing was changed
      assert:
        that:
          - result is not changed
