---
language: python

services:
  - docker

python:
  - '3.6'

install:
  - pip install molecule docker black
  - docker build -t danihodovic/ansible-samson-test -f Dockerfile.test .

script:
  - black --check library
  - molecule test --all
