FROM danihodovic/samson:attributes

ENV RAILS_LOG_TO_STDOUT=1
ENV DATABASE_URL=sqlite3:///app/db/development.sqlite3

RUN apt install sqlite3
RUN bundle install --local --quiet --jobs 4

COPY ./bootstrap_test_db.sh /app/
RUN bash /app/bootstrap_test_db.sh

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
