---
- name: Inbound webhook tests
  hosts: molecule-samson
  tasks:
    - name: Create a random permalink to not clash with other tests
      set_fact:
        permalink: '{{ 99999999 | random | to_uuid }}'

    - name: Create a project
      register: project_result
      samson_project:
        url: http://localhost:9080
        token: token
        permalink: '{{ permalink }}'
        name: dotfiles
        repository_url: https://github.com/danihodovic/.dotfiles

    - name: Create a stage
      register: stage_result
      samson_stage:
        url: http://localhost:9080
        token: token
        project_permalink: '{{ permalink }}'
        permalink: '{{ permalink }}'
        name: test

    - name: Create a webhook
      register: create_result
      samson_inbound_webhook: &create_params
        url: http://localhost:9080
        token: token
        project_id: '{{ project_result.project.id }}'
        stage_id: '{{ stage_result.stage.id }}'
        branch: 'my_branch'
        source: 'travis'

    - name: Assert that the task was executed correctly
      assert:
        that:
          - create_result.changed == true
          - create_result.webhook.stage_id == stage_result.stage.id
          - create_result.webhook.branch == 'my_branch'
          - create_result.webhook.source == 'travis'
          - create_result.webhook.id is defined

    - name: Create with the same params
      register: create_result_2
      samson_inbound_webhook:
        <<: *create_params

    - name: Assert that nothing is changed
      assert:
        that:
          - create_result_2.changed == false
          - create_result_2.webhook.id is defined

    - name: Delete
      register: delete_result
      samson_inbound_webhook:
        <<: *create_params
        state: absent

    - name: Assert that the deletion returned a changed task
      assert:
        that:
          - delete_result is changed

    - name: Delete again
      register: delete_again_result
      samson_inbound_webhook:
        <<: *create_params
        state: absent

    - name: Assert that nothing was changed
      assert:
        that:
          - delete_again_result is not changed
