---
- set_fact:
    samson_env: '{{ samson_env_defaults | combine(samson_env) }}'

- name: Assert that we have a deploy key
  assert:
    that:
      - samson_ssh_key is defined
      - samson_env.DEFAULT_URL is defined
      - samson_env.DEFAULT_URL.startswith("http")

- name: Create directory
  file:
    path: '{{ samson_dir }}/ssh'
    state: directory

- name: Copy ssh key to clone private repositories
  no_log: true
  copy:
    content: '{{ samson_ssh_key }}'
    dest: '{{ samson_dir }}/ssh/id_rsa'
    mode: 0400

- name: Copy files
  copy:
    content: '{{ samson_dockerfile_content }}'
    dest: '{{ samson_dir }}/Dockerfile'

- name: Build Samson image
  docker_image:
    build:
      pull: true
      path: '{{ samson_dir }}'
    source: build
    force_source: true
    name: '{{ samson_image }}'

- name: Start Samson
  notify: health_check_samson
  no_log: '{{ no_log | default(true) }}'
  docker_container:
    comparisons:
      '*': strict
    name: samson
    image: '{{ samson_image }}'
    state: started
    restart_policy: unless-stopped
    networks: '{{ samson_docker_networks }}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '{{ samson_dir }}/db:/db/'
      - '{{ samson_dir }}/ssh/:/root/.ssh/:ro'
    env: '{{ samson_env }}'

- name: Wait for Samson to start
  register: health_check_result
  shell: >-
    docker run --net=container:samson
    alpine/httpie --check-status GET http://samson:{{ samson_env.PORT }}/ping
    Host:localhost
  retries: 30
  delay: 1
  until: health_check_result.rc == 0
  changed_when: false
