---
- name: Default
  hosts: molecule-samson
  tasks:
    - name: Create a random permalink to not clash with other tests
      set_fact:
        permalink: '{{ 99999999 | random | to_uuid }}'

    - name: Create a project
      register: project
      samson_project:
        url: http://localhost:9080
        token: token
        permalink: '{{ permalink }}'
        name: dotfiles
        repository_url: https://github.com/danihodovic/.dotfiles

    - name: Create command
      register: command
      samson_command:
        url: http://localhost:9080
        token: token
        command: 'echo "hello from samson-ansible"'
        project_id: '{{ project.project.id }}'

    - name: Create a stage
      register: stage
      samson_stage:
        url: http://localhost:9080
        token: token
        project_permalink: '{{ permalink }}'
        permalink: '{{ permalink }}'
        name: test
        command_ids:
          - '{{ command.command.id }}'
