---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: molecule-samson
    image: zendesk/samson:latest
    pre_build_image: true
    command: >
      bash -c '
      bundle install --local --quiet --jobs 4 || bundle check &&
      RAILS_DUMP_SCHEMA=false bundle exec rake db:create db:schema:load db:migrate &&
      bundle exec puma -C config/puma.rb
      '
    published_ports:
      - '9080:9080'
    env:
      DATABASE_URL: 'sqlite3:///app/db/development.sqlite3'
      RAILS_LOG_TO_STDOUT: 1
provisioner:
  name: ansible
  env:
    ANSIBLE_MODULE_UTILS: ../../module_utils
  lint:
    name: ansible-lint
    options:
      x: [ANSIBLE0011]
  playbooks:
    converge: ./converge.yml
    prepare: ../shared/prepare.yml
scenario:
  name: delete_command
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - destroy
