---
- name: Create stage
  hosts: molecule-samson
  tasks:
    - name: Create a random permalink to not clash with other tests
      set_fact:
        project_permalink: p
        stage_permalink: s
        # project_permalink: '{{ 99999999 | random | to_uuid }}'
        # stage_permalink: '{{ 99999999 | random | to_uuid }}'

    - name: Create a project
      register: project_result
      samson_project:
        url: http://localhost:9080
        token: token
        permalink: '{{ project_permalink }}'
        name: dotfiles
        repository_url: https://github.com/danihodovic/.dotfiles

    - name: Create a stage
      register: result
      samson_stage:
        url: http://localhost:9080
        token: token
        project_permalink: '{{ project_permalink }}'
        permalink: '{{ stage_permalink }}'
        name: test
        slack_webhooks_attributes:
          - webhook_url: https://myslack.org
            # channel: '#devops'
            buddy_box: true
            # buddy_request: true
            before_deploy: true
            on_deploy_success: true
            on_deploy_failure: true
            # id: 199

    - set_fact:
        stage: '{{ result.stage }}'

    - name: Assert that the task was executed correctly
      assert:
        that:
          - result.changed == true
          - stage.project_id == project_result.project.id
          - stage.permalink == '{{ stage_permalink }}'
          - stage.name == 'test'
