---
- name: Create stage
  hosts: molecule-samson
  tasks:
    - name: Create a random permalink to not clash with other tests
      set_fact:
        project_permalink: '{{ 99999999 | random | to_uuid }}'
        stage_permalink: '{{ 99999999 | random | to_uuid }}'

    - name: Create a project
      register: project_result
      samson_project:
        url: http://localhost:9080
        token: token
        permalink: '{{ project_permalink }}'
        name: dotfiles
        repository_url: https://github.com/danihodovic/.dotfiles

    - name: Create a stage
      register: result
      samson_stage:
        url: http://localhost:9080
        token: token
        project_permalink: '{{ project_permalink }}'
        permalink: '{{ stage_permalink }}'
        name: test

    - set_fact:
        stage: '{{ result.stage }}'

    - name: Assert that the task was executed correctly
      assert:
        that:
          - result is changed
          - stage.project_id == project_result.project.id
          - stage.permalink == '{{ stage_permalink }}'
          - stage.name == 'test'
